openapi: 3.2.0
info:
  title: Platzi Fake Store Files API
  description: ''
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Files
paths:
  /api/v1/files/upload:
    post:
      operationId: FilesController_uploadFile
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Files
      summary: Files controller upload file
      x-summary-source: derived
  /api/v1/files/{filename}:
    get:
      operationId: FilesController_seeUploadedFile
      parameters:
      - name: filename
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Files
      summary: Files controller see uploaded file
      x-summary-source: derived
